enrich.api.endpoint=http://localhost:8080/

# MongoDB configuration
#enrich.mongodb.connectionUri=mongodb://localhost:27017
#enrich.mongodb.database=enrichment
#db for keyword ui
#enrich.mongodb.database=keywords

# Named entity linking section
enrich.ner.linking.europeana.apikey=apidemo

# Translation
# Translation Google configuration
enrich.translation.google.credentials=/opt/app/enrich/secrets/gtanslate.json
enrich.translation.google.waittime=2
# Translation eTranslation configuration
enrich.translation.eTranslation.credentials=/opt/app/enrich/secrets/eTranslation.txt

# 	eTranslation domain could be GEN or "SPD" (for neural and speed-optimized statistical engines on the cloud. This is the default.) else "Europeana"
enrich.translation.eTranslation.domain=GEN

#enrich.solr.translated.entities=http://localhost:8983/solr/solr-enrichment
solr.timeout = 60000
solr.facetLimit=750

# used for saving Wikidata info into files ${enrich.directory}/wikidata
enrich.directory = /opt/app/enrich/data/
enrich.wikidata.json.base.url=https://www.wikidata.org/wiki/Special:EntityData/

#string value representing the key used for JWT signature verification 
#europeana.apikey.jwttoken.signaturekey=<signature key>
# Resource name embedded in JWT token
authorization.api.name=entities
# Useful for local development. If false, unauthenticated read/write requests can be sent to API
auth.read.enabled=true
auth.write.enabled=true
europeana.apikey.serviceurl=https://apikey.eanadev.org/apikey