resources:
  - deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app: stanford-ner-en
          
#generate config mapping for log4j2.xml file
configMapGenerator:
  - name: log4j2-properties
    files:
      - log4j2-spring.xml
          