# Named entity recognition and classification section
# NER Stanford classifier configuration
#enrich.ner.stanford.model=/stanford/classifiers/english.all.3class.distsim.crf.ser.gz
enrich.ner.stanford.model=/stanford/classifiers/english.conll.4class.distsim.crf.ser.gz

