resources:
  - deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app: enrichment-web

# expects files to be in the same directory
secretGenerator:
  - name: enrichment-web-properties
    files:
      - enrichment.user.properties
  - name: gtanslate-secret
    files:
      - ./secrets/gtanslate.json
  - name: etanslate-secret
    files:
      - ./secrets/eTranslation.txt
  - name: deepl-secret
    files:
      - ./secrets/deeplAuthentication.txt
          
#generate config mapping for log4j2.xml file
configMapGenerator:
  - name: log4j2-properties
    files:
      - log4j2-spring.xml
          